name: Annafi Ikhwanul Azis
title: Nafi | Passionate Designer
email: annafi_@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello you there, here is Annafi portfolio site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "nafinafi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: https://nafinafi.github.io/img/logo.png
resume: https://nafinafi.github.io/resume.pdf

social:
  - title: email
    url:  mailto:annafi_@outlook.com
  - title: linkedin
    url: https://www.linkedin.com/in/nafi
posts:
  - title: Satu Persen
    url: /_posts/2017-07-26-name.md

# Build settings
markdown: 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

keep_files:
  - '.gitignore'